pittletsv2/urls.py
from django.contrib import admin
from django.urls import include, path
import app
from app.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', app.views.home, name='home'),
    path('about/', app.views.about, name='about'),
    path('signup/', app.views.signup, name = 'signup'),
    path('post/', app.views.post, name = 'post'),
    path('listing/<int:listing_id>', app.views.listing_post, name = 'listing_post'),
    path('edit/<int:listing_id>', app.views.edit, name = 'edit'),
    path('delete/<int:listing_id>', app.views.delete, name = 'delete'),
    path('search/', app.views.search, name = 'search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from .models import Listing, Image
from django.contrib.auth.forms import UserCreationForm
from django.forms import formset_factory

class ListingForm(forms.ModelForm, forms.Form):
    typeChoice = [('Sublet', 'Sublet'), ('Pass on Lease', 'Pass on Lease')]
    type = forms.ChoiceField(choices = typeChoice, widget = forms.RadioSelect())
    amenities = forms.MultipleChoiceField(
        choices=[('AC','Air-Conditioning'), ('Doorman','Doorman'), ('Furnished', 'Furnished'),
                 ('Utilities', 'Utilities Included'), ('Wifi', 'Wifi'), ('Laundry', 'Washer/Dryer'), ('Pets', 'Pets Allowed'), ('Gym', 'Gym')],  # this is optional
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'new_form'}),
    )
    # need to integrate amenities with the new model
    class Meta:
        model = Listing
        widgets = {
            'description': forms.Textarea(
                attrs={'placeholder': 'Enter your description here'}),
        }
        fields = [
            'title',
            'description',
            'size',
            'address',
            'price',
            'prorated',
        ]

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    username = forms.CharField(max_length=20)


    # First checks validity of super user, then checks if the email supplied is a valid .edu address
    def is_valid(self):
        valid = super(UserCreationForm, self).is_valid()

        if not valid:
            return valid

        if '.edu' not in self.data['email']:
            return False

        return True


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label = 'image')
    class Meta:
        model = Image
        fields = ('image', )

class filterForm(forms.Form):
    typeChoice = [('Sublet', 'Sublet'), ('Pass on Lease', 'Pass on Lease')]
    type = forms.ChoiceField(choices=typeChoice, widget=forms.RadioSelect())
    amenities = forms.MultipleChoiceField(
        choices=[('AC', 'Air-Conditioning'), ('Doorman', 'Doorman'), ('Furnished', 'Furnished'),
                 ('Utilities', 'Utilities Included'), ('Wifi', 'Wifi'), ('Laundry', 'Washer/Dryer'),
                 ('Pets', 'Pets Allowed'), ('Gym', 'Gym')],  # this is optional
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'new_form'}),
    )

templates/about.html
{% extends "./layout.html" %}
{% load static %}

{% block content %}
    <br>
    <p>
        Pittlets was created because subletting at CMU sucked and relied entirely on a Facebook group to do everything. When I was in Philadelphia last summer, UPenn students used a site called Pennlets to
        handle all of their subletting, and it was a godsend.
        I've also been very wary of subletting from strangers if they weren't a student because students just want to make sure they aren't wasting their rent while landlords might want to make a profit.
    </p>
    <p>
        I'm not putting on ads or any kind of revenue generating thing on here. If this service has helped you,
        please <a href = "https://www.yelp.com/user_details?userid=XCZm0RRjnvz54mZGP25_cg";>consider liking all my reviews on Yelp</a>
        so I can get Yelp elite.
    </p>

    <br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock content %}

templates/home.html
{% extends "./layout.html" %}
{% load static %}


{% block content %}
<br>
<div class="first-column" ;>
    <ul>
        {% for listing in listings %}
            <br>
            <div class = 'home_posting' style = 'display:inline'>
                <a style = 'line-height: 40px; font-size: 36px; color:#273342;' href = {% url 'listing_post' listing.id %}> {{ listing.title }} </a>
                <br><br>
                <div style = 'font-size: 12px;'>
                    {% for image in list_of_image_querysets %}
                        {% if image.post == listing %}
                            <div class = 'listing_image_container'>
                                <img id = 'small_img' class = "listing_image"; src = "../../media/{{ image.photo }}">
                                <img id = 'big_img' class = 'listing_big_image'; src = "../../media/{{ image.photo }}">
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div style = 'display: inline-block; max-width: 50%; padding-left: 10px;'>
                        <b>Date Listed:</b> {{ listing.pub_date }} <br>
                        <b>Rent:</b> ${{ listing.price }} <br>
                        <b>Size:</b> {{ listing.size }} <br>
                        <b>Address:</b> {{ listing.address }} <br>
                        <b>Type of Listing:</b> {{ listing.type }} <br>
                        <b>Amenities:</b> {{ listing.amenities }} <br>
                        {% if listing.prorated is not False %}
                            <b>Prorated:</b> Yes
                        {%  else %}
                            <b>Prorated:</b> No
                        {%  endif %}

                    </div>

                    <p>
                        <b>Description: </b>
                        {{ listing.description }}
                    </p>
                </div>

            </div>
            <hr>
        {% endfor %}
    </ul>

    {% if listings.has_other_pages %}
      <ul class="pagination">
        {% if listings.has_previous %}
          <div class = 'arrow';><a href="?page={{ listings.previous_page_number }}">&laquo; prev </a></div>
        {% endif %}
        {% for i in users.paginator.page_range %}
          {% if listings.number == i %}
            <div class="arrow"><span>{{ i }} <span class="sr-only">(current)</span></span></div>
          {% else %}
            <div class = 'arrow';><a href="?page={{ i }}">{{ i }}</a></div>
          {% endif %}
        {% endfor %}
        {% if listings.has_next %}
          <div class = 'arrow';><a href="?page={{ listings.next_page_number }}">next &raquo;</a></div>
        {% endif %}
      </ul>
    {% endif %}
</div>

<div class="second-column" ;>
    <br>
    <h1 style="text-decoration:underline; color:#121212;"> faq.</h1>
    <b>You must register with an .edu email address and login to post and inquire about listings. </b>

    <h3 style="text-decoration:underline; color:#121212;"> Looking for a place to sublet/rent?</h3>
    Simply go through the listings or use filters to cut down the search.

    <h3 style="text-decoration:underline; color:#121212;"> Looking to put your place up for rent?</h3>
    Simply click on "post listing" and fill out the appropriate forms.

    <h3 style="text-decoration:underline; color:#121212;"> Want to help prevent me from dropping out of school?</h3>
    Please rate my reviews on <a href = "https://www.yelp.com/user_details?userid=XCZm0RRjnvz54mZGP25_cg";>Yelp</a> and I might consider it.
</div>

{% endblock content %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>pittlets</title>
</head>
<body>
    <div class = 'header'>
        <div class = 'header-top'>
            <div class = 'header-left'>
                <a href =  {% url 'about' %}>about pittlets</a>
            </div>
            <div class = 'header-right'>
                Welcome,
                {% if is_authenticated is True %}
                    {{ user.username }}
                    | <a href = {% url 'logout' %}>logout</a> <!-- should be signout !-->
                {% else %}
                    Guest!
                    | <a href = {% url 'signup' %}>register</a>/<a href = {% url 'login' %}>login</a>
                {% endif %}

            </div>

            <br>

            <a style = "opacity: 1;" href = {% url 'home' %} >
                <img class = "centered_image" src = "{% static 'images/logo.png' %}"></img>
            </a>
        </div>

        <br>

        <!-- This is the bottom part of the header -->
        <div class = 'strip'>
            <div class = 'strip-content'>
                <div class = 'strip-content-left'>
                    <form name = 'search_form' type = 'get' action = "{% url 'search' %}">
                        <input name = 'search_box' class = 'search'; type="text" placeholder="Search..">
                        <button id = 'search_submit' type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <div class = 'strip-content-right'>
                    <a class = 'post' style = "opacity:1;" href= {% url 'post' %}>
                        post listing
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class = 'content'>
        {% block content %}
        {% endblock content %}
    </div>

    </div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
</body>
</html>

templates/listing.html
{% extends "./layout.html" %}
{% load static %}

{% block content %}
    <style>
        .second-column a {
            opacity: 1;
            text-decoration: underline;
            color: #7092BE;
        }

        .second-column a:hover {
            opacity: .7;
            text-decoration: underline;
        }
    </style>
    <br>
    <br>

    <div class = 'first-column'>
        <div class = "listing_title";> {{ listing.title }} </div>
        <br>
        <img style = 'max-width:100%; max-height:900px;' src = "../../media/{{ images.photo }}">
        <br>

        {% if cur_user == listing.user %}
            <a href = {% url 'edit' listing.id %}> update </a> --
            <a href = {% url 'delete' listing.id %}> delete </a>
            <br>
        {% endif %}

        <div class = 'listing_descriptor'> Size:  </div> <div class = 'listing_value'>{{ listing.size }} </div>
        <br>
        <div class = 'listing_descriptor'> Type of Listing:  </div> <div class = 'listing_value'>{{ listing.type }} </div>
        <br>
        <div class = 'listing_descriptor'> Address:  </div> <div class = 'listing_value'>{{ listing.address }} </div>
        <br>
        <div class = 'listing_descriptor'> Amenities:  </div> <div class = 'listing_value'>{{ listing.amenities }} </div>
        <br>
        <div class = 'listing_descriptor'> Date Listed:  </div> <div class = 'listing_value'>{{ listing.pub_date }} </div>
        <br>
        <div class = 'listing_descriptor'> Prorated:  </div>

        {% if listing.prorated is not False %}
            <div class = 'listing_value'> Yes </div>
        {% else %}
            <div class = 'listing_value'> No </div>
        {% endif %}
        <br>
        <div class = 'listing_descriptor'> Price:  </div> <div class = 'listing_value'>{{ listing.price }} </div>
        <br>
        <br>
        <div class = 'listing_description'> Description:  </div> <div class = 'listing_value'>{{ listing.description }} </div>
    </div>

    <div class = 'second-column'>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <iframe height = "300" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/search?key=AIzaSyBgMWAy-8dJcNhF1ibTRiU_7Omem4bGexY&q={{ listing.address }}" allowfullscreen> </iframe>
        <br>
        <br>
        <div class = "listing_title";> Contact </div>
        {% if is_authenticated is not False %}
            {{ owner.email }}
        {% else %}
            You must log in to see contact information
        {% endif %}

        <h3 style="text-decoration:underline; color:#121212;"> Tips for not getting scammed</h3>
        DO NOT SEND PAYMENT THROUGH VENMO.
        <br>
        BE WARY OF PEOPLE PUTTING THEIR CONTACT INFO IN THEIR MESSAGE. If their contact info does not match their registered email address, there is no way to no if they are a student.

        <h3 style="text-decoration:underline; color:#121212;"> Looking to put your place up for rent?</h3>
        Simply click on "post listing" and fill out the appropriate forms.

        <h3 style="text-decoration:underline; color:#121212;"> Want to help prevent me from dropping out of school and becoming a hermit?</h3>
        Please rate my reviews on <a href = "https://www.yelp.com/user_details?userid=XCZm0RRjnvz54mZGP25_cg";>Yelp</a> and I might consider it.
        </div>
    </div>



{% endblock content %}

templates/post.html
{% extends "./layout.html" %}

{% block content %}


    <style>
        .new_form {
            list-style-type: none !important;
            list-style: none !important;
        }

        textarea {
            width: 100%;
            height: 200px;

        }

        #id_type {
            list-style-type: none !important;
            list-style: none !important;
        }

    </style>

    <div style = "list-style-type: none;">
    <h2>Post a listing</h2>
    {{ form.management_form }}
    {{ formset.management_form }}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formset.management_form }}
        {% for newform in formset %}
            {{ newform }}
        {% endfor %}
        <br>
        <br>
        <br>
        <br>
        <button type="submit" value="submit">Post my listing!</button>
    </form>
    </div>

{% endblock content %}

templates/search.html
{% extends "./layout.html" %}
{% load static %}


{% block content %}
    <style>
        #id_amenities {
            list-style-type: none !important;
            list-style: none !important;
        }

        textarea {
            width: 100%;
            height: 200px;

        }

        #id_type {
            list-style-type: none !important;
            list-style: none !important;
        }

        .button {
            background-color: #7092BE;
            border: none;
            color: white;
            padding: 10px 30px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
            opacity: 1;
        }

        .button:hover {
            opacity: 0.8;
        }
    </style>
    <br>
    <div class="first-column" ;>
        <ul>
            {% for listing in listings %}
                <br>
                <div class = 'home_posting' style = 'display:inline'>
                    <a style = 'line-height: 40px; font-size: 36px; color:#273342;' href = {% url 'listing_post' listing.id %}> {{ listing.title }} </a>
                    <br><br>
                    <div style = 'font-size: 12px;'>
                        {% for image in list_of_image_querysets %}
                            {% if image.post == listing %}
                                <div class = 'listing_image_container'>
                                    <img id = 'small_img' class = "listing_image"; src = "../../media/{{ image.photo }}">
                                    <img id = 'big_img' class = 'listing_big_image'; src = "../../media/{{ image.photo }}">
                                </div>
                            {% endif %}
                        {% endfor %}
                        <div style = 'display: inline-block; max-width: 50%; padding-left: 10px;'>
                            <b>Date Listed:</b> {{ listing.pub_date }} <br>
                            <b>Rent:</b> ${{ listing.price }} <br>
                            <b>Size:</b> {{ listing.size }} <br>
                            <b>Address:</b> {{ listing.address }} <br>
                            <b>Type of Listing:</b> {{ listing.type }} <br>
                            <b>Amenities:</b> {{ listing.amenities }} <br>
                            {% if listing.prorated is not False %}
                                <b>Prorated:</b> Yes
                            {%  else %}
                                <b>Prorated:</b> No
                            {%  endif %}

                        </div>

                        <p>
                            <b>Description: </b>
                            {{ listing.description }}
                        </p>
                    </div>

                </div>
                <hr>
            {% endfor %}
        </ul>

        {% if listings.has_other_pages %}
          <ul class="pagination">
            {% if listings.has_previous %}
              <div class = 'arrow';><a href="?page={{ listings.previous_page_number }}">&laquo; prev </a></div>
            {% endif %}
            {% for i in users.paginator.page_range %}
              {% if listings.number == i %}
                <div class="arrow"><span>{{ i }} <span class="sr-only">(current)</span></span></div>
              {% else %}
                <div class = 'arrow';><a href="?page={{ i }}">{{ i }}</a></div>
              {% endif %}
            {% endfor %}
            {% if listings.has_next %}
              <div class = 'arrow';><a href="?page={{ listings.next_page_number }}">next &raquo;</a></div>
            {% endif %}
          </ul>
        {% endif %}
    </div>

    <div class="second-column" ;>
        <br>
        <form name = 'search_filter' type = 'get' action = "{% url 'search' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button class = 'button' type="submit" value = "search">Filter</button>
        </form>
        <br>
        <br>
        <br>
        <br>
        <h1 style="text-decoration:underline; color:#121212;"> faq.</h1>
        <b>You must register with an .edu email address and login to post and inquire about listings. </b>

        <h3 style="text-decoration:underline; color:#121212;"> Looking for a place to sublet/rent?</h3>
        Simply go through the listings or use filters to cut down the search.

        <h3 style="text-decoration:underline; color:#121212;"> Looking to put your place up for rent?</h3>
        Simply click on "post listing" and fill out the appropriate forms.

        <h3 style="text-decoration:underline; color:#121212;"> Want to help prevent me from dropping out of school?</h3>
        Please rate my reviews on <a href = "https://www.yelp.com/user_details?userid=XCZm0RRjnvz54mZGP25_cg";>Yelp</a> and I might consider it.
    </div>

{% endblock content %}

templates/signup.html
{% extends "./layout.html" %}


{% block content %}
    <style>
    a {
        opacity: 0.5;
    }
    a:hover{
        opacity: 1;
    }
    </style>

    <div class = 'first-column'>
        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" value = "signup">Sign up</button>
        </form>

    </div>

    <div class = 'second-column'>
        <h2>Already have an account?</h2>
        <a href = {% url 'login' %}> Go here </a>
    </div>
{% endblock content %}